- name: Install misc packages
  become: yes
  apt:
    name: 
      - curl
      - xdotool
      - wmctrl
      - git
      - vim
      - gcc
      - make
      - automake
      - autoconf
      - python-pip
      - python3-pip
      - ruby
      - pavucontrol

- name: Install misc python packages
  pip:
    name:
      - meson
    executable: pip3
    state: present
