- name: Install dependencies
  become: yes
  apt:
    name:
      - libdbus-1-dev
      - libxcursor-dev
      - libxrandr-dev
      - libxi-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libxkbcommon-x11-dev
      - libfontconfig-dev
      - libpython-dev
      - libharfbuzz-dev

- name: Clone kitty repo
  git:
    repo: https://github.com/Lixxia/kitty.git
    dest: '{{user_home}}/repos/kitty'

- name: Build kitty
  make:
    chdir: '{{user_home}}/repos/kitty'

- name: Setup link
  become: yes
  file:
    src: '{{user_home}}/repos/kitty/kitty/launcher/kitty'
    dest: /usr/local/bin/kitty
    state: link
