- name: Create fonts dir
  file:
    path: ~/.local/share/fonts
    state: directory

- name: Install Iosevka Medium
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Iosevka/Medium/complete/Iosevka%20Medium%20Nerd%20Font%20Complete%20Mono.ttf
      dest: "~/.local/share/fonts/Iosevka Medium Nerd Font Complete Mono.ttf"

- name: Install Iosevka Medium
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Iosevka/Regular/complete/Iosevka%20Nerd%20Font%20Complete%20Mono.ttf
      dest: "~/.local/share/fonts/Iosevka Nerd Font Complete Mono.ttf"

- name: Symlink fonts dir
  file:
    src: ~/.local/share/fonts
    dest: ~/.fonts
    state: link

- name: Update font cache
  command: fc-cache -f

# test font with fc-match or fc-list?
# add fontawesome 5
