- name: Create fonts dir
  file:
    path: ~/.local/share/fonts
    state: directory

- name: Install Iosevka Medium
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/Medium/complete/Iosevka%20Medium%20Nerd%20Font%20Complete.ttf
      dest: "~/.local/share/fonts/Iosevka Medium Nerd Font Complete.ttf"

- name: Install Iosevka Regular Mono
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/Bold/complete/Iosevka%20Bold%20Nerd%20Font%20Complete.ttf
      dest: "~/.local/share/fonts/Iosevka Bold Nerd Font Complete.ttf"

- name: Install Font Awesome
  get_url:
    url: https://use.fontawesome.com/releases/v5.14.0/fontawesome-free-5.14.0-desktop.zip
    dest: /tmp/fontawesome-free-5.14.0-desktop.zip

- name: Unarchive Font Awesome
  unarchive:
    src: /tmp/fontawesome-free-5.14.0-desktop.zip
    dest: /tmp

- name: Grab otfs
  copy:
    src: '/tmp/fontawesome-free-5.14.0-desktop/otfs/{{item}}'
    dest: '~/.local/share/fonts/{{item}}'
  with_items: 
    - 'Font Awesome 5 Brands-Regular-400.otf'
    - 'Font Awesome 5 Free-Regular-400.otf'
    - 'Font Awesome 5 Free-Solid-900.otf'

- name: Symlink fonts dir
  file:
    src: ~/.local/share/fonts
    dest: ~/.fonts
    state: link

- name: Update font cache
  command: fc-cache -f
